### ISSUE TITLE
Use of SASS

### ISSUE THREAD

**Issue by uspsureshot** [preetha5/fewd2_final#2]
Not sure how we are going to keep track of this without using SASS.  This CSS file is going to get very complicated.  

I can push up my SASS structure so we can all come together if you are willing.  Otherwise we will have to pull CSS and Preetha Will have to stay on top of the commits or else we will step on toes.

'If y'all need help with SASS I'm happy to help.  I am also brushing up on my Git to be able to be more help there.

**Comment by preetha5** [comment]
I'm fine with doing SASS if everyone is onboard.  But maintaining 2 files seems both CSS and SASS will be overkill . I can convert my existing CSS to SASS now before proceeding with my next checkin.

**Comment by uspsureshot** [comment]
It's easier to work in Sass sections. For Forms I have a _Forms.scss file.as
long as I make all the form changes there, I step on no toes.

I will do as the majority rules.

Gregor
